baseURL = "http://192.168.65.140:1313/"
title = "潤宏水産"
theme = "ananke"

DefaultContentLanguage = "ja"

[languages]
  [languages.ja]
    languageName = "Japanese"
    weight = 20
    title = "潤宏水産"
  [languages.zh]
    languageName = "Chinese"
    weight = 20
    title = "润宏水产"
