baseURL = "https://rh-aquatic.com"
title = "潤宏水産"
theme = "ananke"

DefaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[languages]
  [languages.ja]
    languageName = "Japanese"
    weight = 20
    title = "潤宏水産"
  [languages.zh]
    languageName = "Chinese"
    weight = 20
    title = "润宏水产"

[[languages.zh.menu.main]]
  name = "主页"
  url = "#about"
  weight = 1
[[languages.ja.menu.main]]
  name = "ホーム"
  url = "#about"
  weight = 1
